/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SimpleAuctionInterface extends Interface {
    getFunction(nameOrSignature: "bid" | "endAuction" | "endTime" | "ended" | "highestBid" | "highestBidder" | "owner" | "pendingRefunds" | "startTime" | "startingPrice" | "withdrawRefund"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionFinalized" | "BidPlaced" | "Refunded"): EventFragment;

    encodeFunctionData(functionFragment: 'bid', values?: undefined): string;
encodeFunctionData(functionFragment: 'endAuction', values?: undefined): string;
encodeFunctionData(functionFragment: 'endTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'ended', values?: undefined): string;
encodeFunctionData(functionFragment: 'highestBid', values?: undefined): string;
encodeFunctionData(functionFragment: 'highestBidder', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingRefunds', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'startTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'startingPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawRefund', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'bid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ended', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'highestBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'highestBidder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingRefunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startingPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawRefund', data: BytesLike): Result;
  }

  
    export namespace AuctionFinalizedEvent {
      export type InputTuple = [winner: AddressLike, winningBid: BigNumberish];
      export type OutputTuple = [winner: string, winningBid: bigint];
      export interface OutputObject {winner: string, winningBid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [bidder: string, amount: bigint];
      export interface OutputObject {bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [bidder: string, amount: bigint];
      export interface OutputObject {bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SimpleAuction extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleAuction;
    waitForDeployment(): Promise<this>;

    interface: SimpleAuctionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bid: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    endAuction: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    endTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ended: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    highestBid: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    highestBidder: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingRefunds: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    startTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    startingPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdrawRefund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bid'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ended'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'highestBid'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'highestBidder'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingRefunds'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'startTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'startingPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawRefund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuctionFinalized'): TypedContractEvent<AuctionFinalizedEvent.InputTuple, AuctionFinalizedEvent.OutputTuple, AuctionFinalizedEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;

    filters: {
      
      'AuctionFinalized(address,uint256)': TypedContractEvent<AuctionFinalizedEvent.InputTuple, AuctionFinalizedEvent.OutputTuple, AuctionFinalizedEvent.OutputObject>;
      AuctionFinalized: TypedContractEvent<AuctionFinalizedEvent.InputTuple, AuctionFinalizedEvent.OutputTuple, AuctionFinalizedEvent.OutputObject>;
    

      'BidPlaced(address,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    

      'Refunded(address,uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    
    };
  }